### ISSUE TITLE
main process exited, code=exited, status=1/FAILURE

### ISSUE THREAD

**Issue by ballle98** [ballle98/AqualinkD#37]
```
Aug 05 13:08:55 raspberrypi aqualinkd[14602]:         AqualinkD is using PDA mode
Aug 05 13:08:55 raspberrypi aqualinkd[14602]: AqualinkD is using PDA mode
Aug 05 13:08:55 raspberrypi aqualinkd[14602]: Aqualink Daemon v1.3.4a
Aug 05 13:08:55 raspberrypi aqualinkd[14602]: Config log_level         = 5
Aug 05 13:08:55 raspberrypi aqualinkd[14602]: Config socket_port       = 80
Aug 05 13:08:55 raspberrypi aqualinkd[14602]: Config serial_port       = /dev/ttyUSB0
Aug 05 13:08:55 raspberrypi aqualinkd[14602]: Config web_directory     = /var/www/aqualinkd/
Aug 05 13:08:55 raspberrypi aqualinkd[14602]: 13:08:55.775 Notice: AqualinkD is using PDA mode
Aug 05 13:08:56 raspberrypi systemd[1]: Started Aqualink RS daemon.
Aug 05 13:08:55 raspberrypi aqualinkd[14603]: Starting web server on port 80
Aug 05 13:08:55 raspberrypi aqualinkd[14603]: Starting MQTT client to (null)
Aug 05 13:08:55 raspberrypi aqualinkd[14603]: Listening to Aqualink RS8 on serial port: /dev/ttyUSB0
Aug 05 13:08:55 raspberrypi aqualinkd[14603]: AqualinkD is using PDA mode
Aug 05 15:21:29 raspberrypi aqualinkd[14603]: waitForPDAMessageTypesOrMenu 0x09,0xff,(null),0 - Connection timed out
Aug 05 15:21:29 raspberrypi aqualinkd[14603]: waitForPDAMessageTypesOrMenu: did not receive 0x09 or 0xff
Aug 05 15:21:32 raspberrypi aqualinkd[14603]: waitForPDAMessageTypesOrMenu 0x08,0x10,(null),0 - Connection timed out
Aug 05 15:21:32 raspberrypi aqualinkd[14603]: waitForPDAMessageTypesOrMenu: did not receive 0x08 or 0x10
Aug 05 15:21:32 raspberrypi aqualinkd[14603]: PDA Device programmer selected menu item EQUIPMENT ON/OFF wait for next menu failed
Aug 05 15:21:32 raspberrypi systemd[1]: aqualinkd.service: Main process exited, code=exited, status=1/FAILURE
Aug 05 15:21:32 raspberrypi systemd[1]: aqualinkd.service: Unit entered failed state.
Aug 05 15:21:32 raspberrypi systemd[1]: aqualinkd.service: Failed with result 'exit-code'.
Aug 05 15:21:34 raspberrypi systemd[1]: aqualinkd.service: Service hold-off time over, scheduling restart.
Aug 05 15:21:34 raspberrypi systemd[1]: Stopped Aqualink RS daemon.
Aug 05 15:21:34 raspberrypi systemd[1]: Starting Aqualink RS daemon...

```

```
Aug 05 15:21:34 raspberrypi aqualinkd[17972]:         AqualinkD is using PDA mode
Aug 05 15:21:34 raspberrypi aqualinkd[17972]: AqualinkD is using PDA mode
Aug 05 15:21:34 raspberrypi aqualinkd[17972]: Aqualink Daemon v1.3.4a
Aug 05 15:21:34 raspberrypi aqualinkd[17972]: Config log_level         = 5
Aug 05 15:21:34 raspberrypi aqualinkd[17972]: Config socket_port       = 80
Aug 05 15:21:34 raspberrypi aqualinkd[17972]: Config serial_port       = /dev/ttyUSB0
Aug 05 15:21:34 raspberrypi aqualinkd[17972]: Config web_directory     = /var/www/aqualinkd/
Aug 05 15:21:34 raspberrypi aqualinkd[17972]: Config device_id         = 0x62
Aug 05 15:21:34 raspberrypi aqualinkd[17972]: Config read_all_devices  = YES
Aug 05 15:21:34 raspberrypi aqualinkd[17972]: 15:21:34.806 Notice: AqualinkD is using PDA mode
Aug 05 15:21:34 raspberrypi systemd[1]: Started Aqualink RS daemon.
Aug 05 15:21:34 raspberrypi aqualinkd[17973]: Starting web server on port 80
Aug 05 15:21:34 raspberrypi aqualinkd[17973]: Starting MQTT client to (null)
Aug 05 15:21:34 raspberrypi aqualinkd[17973]: Listening to Aqualink RS8 on serial port: /dev/ttyUSB0
Aug 05 15:21:34 raspberrypi aqualinkd[17973]: AqualinkD is using PDA mode
Aug 05 18:07:23 raspberrypi aqualinkd[17973]: Serial read bad checksum, ignoring
Aug 05 18:07:23 raspberrypi aqualinkd[17973]: Bad receive packet  |    Jandy | HEX: 0x10|0x02|0x62|0x04|0x40|0x20|0x20|0x20|0x20|0x20|0x54|0x48|0x55|0x20|0x20|0x37|0x3a|0x10|0x02|0x62|0x04|0x40|0x20|0x20|0x20|0x20|0x20|0x54|0x48|0x55|0x20|0x20|0x37|0x3a|0x34|0x38|0x50|0x4d|0x03|0x10|0x03|
Aug 05 19:39:44 raspberrypi aqualinkd[17973]: PDA Device programmer couldn't find menu item 'EQUIPMENT ON/OFF'
Aug 05 19:39:44 raspberrypi aqualinkd[17973]: PDA Device programmer couldn't selected menu item 'EQUIPMENT ON/OFF' at index 311084
Aug 05 19:39:44 raspberrypi aqualinkd[17973]: PDA Device programmer didn't find a requested menu
Aug 05 19:39:44 raspberrypi aqualinkd[17973]: PDA Device On/Off :- can't find main menu
Aug 05 19:40:16 raspberrypi aqualinkd[17973]: PDA Device programmer couldn't find menu item 'EQUIPMENT ON/OFF'
Aug 05 19:40:16 raspberrypi aqualinkd[17973]: PDA Device programmer couldn't selected menu item 'EQUIPMENT ON/OFF' at index 311084
Aug 05 19:40:16 raspberrypi aqualinkd[17973]: PDA Device programmer didn't find a requested menu
Aug 05 19:40:16 raspberrypi aqualinkd[17973]: PDA Wake Init :- can't find menu
Aug 05 19:59:47 raspberrypi aqualinkd[17973]: Serial read bad checksum, ignoring
Aug 05 19:59:47 raspberrypi aqualinkd[17973]: Bad receive packet  |    Jandy | HEX: 0x10|0x02|0x62|0x04|0x07|0x53|0x50|0x41|0x20|0x48|0x45|0x41|0x54|0x45|0x52|0x20|0x20|0x20|0x20|0x4f|0x4e|0x59|0x10|0xff|0x10|0x02|0x62|0x04|0x07|0x53|0x50|0x41|0x20|0x48|0x45|0x41|0x54|0x45|0x52|0x20|0x20|0x20|0x20|0x4f|0x4e|0x59|0x10|0x03|
Aug 05 21:11:10 raspberrypi systemd[1]: aqualinkd.service: Main process exited, code=exited, status=1/FAILURE
Aug 05 21:11:10 raspberrypi systemd[1]: aqualinkd.service: Unit entered failed state.
Aug 05 21:11:10 raspberrypi systemd[1]: aqualinkd.service: Failed with result 'exit-code'.
Aug 05 21:11:12 raspberrypi systemd[1]: aqualinkd.service: Service hold-off time over, scheduling restart.
Aug 05 21:11:12 raspberrypi systemd[1]: Stopped Aqualink RS daemon.
Aug 05 21:11:12 raspberrypi systemd[1]: Starting Aqualink RS daemon...

```

```
Aug 05 21:11:12 raspberrypi aqualinkd[27205]:         AqualinkD is using PDA mode
Aug 05 21:11:12 raspberrypi aqualinkd[27205]: AqualinkD is using PDA mode
Aug 05 21:11:12 raspberrypi aqualinkd[27205]: Aqualink Daemon v1.3.4a
Aug 05 21:11:12 raspberrypi aqualinkd[27205]: Config log_level         = 5
Aug 05 21:11:12 raspberrypi aqualinkd[27205]: Config socket_port       = 80
Aug 05 21:11:12 raspberrypi aqualinkd[27205]: Config serial_port       = /dev/ttyUSB0
Aug 05 21:11:12 raspberrypi aqualinkd[27205]: Config web_directory     = /var/www/aqualinkd/
Aug 05 21:11:12 raspberrypi aqualinkd[27205]: Config device_id         = 0x62
Aug 05 21:11:12 raspberrypi aqualinkd[27205]: Config read_all_devices  = YES
Aug 05 21:11:12 raspberrypi aqualinkd[27205]: Config use_aux_labels    = YES
Aug 05 21:11:12 raspberrypi aqualinkd[27205]: 21:11:12.307 Notice: AqualinkD is using PDA mode
Aug 05 21:11:12 raspberrypi systemd[1]: Started Aqualink RS daemon.
Aug 05 21:11:12 raspberrypi aqualinkd[27206]: Starting web server on port 80
Aug 05 21:11:12 raspberrypi aqualinkd[27206]: Starting MQTT client to (null)
Aug 05 21:11:12 raspberrypi aqualinkd[27206]: Listening to Aqualink RS8 on serial port: /dev/ttyUSB0
Aug 05 21:11:12 raspberrypi aqualinkd[27206]: AqualinkD is using PDA mode
Aug 05 21:13:48 raspberrypi aqualinkd[27206]: PDA Device programmer couldn't find menu item 'SPA HEAT
                                              '
Aug 05 21:13:48 raspberrypi aqualinkd[27206]: PDA Device On/Off, device 'SPA HEAT' not found
Aug 05 21:13:48 raspberrypi aqualinkd[27206]: PDA Device programmer couldn't find menu item 'POOL LIGHT
                                              '
Aug 05 21:13:48 raspberrypi aqualinkd[27206]: PDA Device On/Off, device 'POOL LIGHT' not found
Aug 05 21:13:48 raspberrypi aqualinkd[27206]: PDA Device programmer couldn't find menu item 'SPA LIGHT
                                              '
Aug 05 21:13:48 raspberrypi aqualinkd[27206]: PDA Device On/Off, device 'SPA LIGHT' not found
Aug 05 21:13:48 raspberrypi aqualinkd[27206]: PDA Device programmer couldn't find menu item 'CLEANER
                                              '
Aug 05 21:13:48 raspberrypi aqualinkd[27206]: PDA Device On/Off, device 'CLEANER' not found
Aug 05 21:13:48 raspberrypi aqualinkd[27206]: PDA Device programmer couldn't find menu item 'POOL HEAT
                                              '
Aug 05 21:13:48 raspberrypi aqualinkd[27206]: PDA Device On/Off, device 'POOL HEAT' not found


```

**Comment by ballle98** [comment]
Aug 16 12:21:29 raspberrypi aqualinkd[29175]:   To 0x53 of type    Probe | HEX: 0x10|0x02|0x53|0x00|0x65|0x10|0x03|
Aug 16 12:21:29 raspberrypi aqualinkd[29175]:   To 0x58 of type    Probe | HEX: 0x10|0x02|0x58|0x00|0x6a|0x10|0x03|
Aug 16 12:21:30 raspberrypi aqualinkd[29175]:   To 0x59 of type    Probe | HEX: 0x10|0x02|0x59|0x00|0x6b|0x10|0x03|
Aug 16 12:21:30 raspberrypi aqualinkd[29175]:   To 0x5a of type    Probe | HEX: 0x10|0x02|0x5a|0x00|0x6c|0x10|0x03|
Aug 16 12:21:30 raspberrypi aqualinkd[29175]:   To 0x5b of type    Probe | HEX: 0x10|0x02|0x5b|0x00|0x6d|0x10|0x03|
Aug 16 12:21:30 raspberrypi aqualinkd[29175]:   To 0x60 of type    Probe | HEX: 0x10|0x02|0x60|0x00|0x72|0x10|0x03|
Aug 16 12:21:30 raspberrypi aqualinkd[29175]:   To 0x61 of type    Probe | HEX: 0x10|0x02|0x61|0x00|0x73|0x10|0x03|
Aug 16 12:21:30 raspberrypi systemd[1]: aqualinkd.service: Main process exited, code=exited, status=1/FAILURE
Aug 16 12:21:30 raspberrypi systemd[1]: aqualinkd.service: Unit entered failed state.
Aug 16 12:21:30 raspberrypi systemd[1]: aqualinkd.service: Failed with result 'exit-code'.

**Comment by ballle98** [comment]
died after ~1 hour

pi@raspberrypi:~/git/AqualinkD $ sudo systemctl status aqualinkd
● aqualinkd.service - Aqualink RS daemon
   Loaded: loaded (/etc/systemd/system/aqualinkd.service; enabled; vendor preset
   Active: active (running) since Fri 2019-08-16 11:12:25 CDT; 12s ago
  Process: 29174 ExecStart=/usr/local/bin/aqualinkd $OPTS (code=exited, status=0
 Main PID: 29175 (aqualinkd)
   CGroup: /system.slice/aqualinkd.service
           └─29175 /usr/local/bin/aqualinkd -c /etc/aqualinkd.conf

Aug 16 11:12:36 raspberrypi aqualinkd[29175]:   To 0x38 of type    Probe | HEX:
Aug 16 11:12:36 raspberrypi aqualinkd[29175]:   To 0x39 of type    Probe | HEX:
Aug 16 11:12:36 raspberrypi aqualinkd[29175]:   To 0x3a of type    Probe | HEX:
Aug 16 11:12:37 raspberrypi aqualinkd[29175]:   To 0x3b of type    Probe | HEX:
Aug 16 11:12:37 raspberrypi aqualinkd[29175]:   To 0x50 of type    Probe | HEX:
Aug 16 11:12:37 raspberrypi aqualinkd[29175]:   To 0x51 of type    Probe | HEX:
Aug 16 11:12:37 raspberrypi aqualinkd[29175]:   To 0x52 of type    Probe | HEX:
Aug 16 11:12:37 raspberrypi aqualinkd[29175]:   To 0x53 of type    Probe | HEX:
Aug 16 11:12:37 raspberrypi aqualinkd[29175]:   To 0x58 of type    Probe | HEX:
Aug 16 11:12:37 raspberrypi aqualinkd[29175]:   To 0x59 of type    Probe | HEX:


pi@raspberrypi:~/git/AqualinkD $ systemctl status aqualinkd
● aqualinkd.service - Aqualink RS daemon
   Loaded: loaded (/etc/systemd/system/aqualinkd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2019-08-16 12:21:30 CDT; 2h 44min ago
  Process: 29174 ExecStart=/usr/local/bin/aqualinkd $OPTS (code=exited, status=0/SUCCESS)
 Main PID: 29175 (code=exited, status=1/FAILURE)

Aug 16 12:21:29 raspberrypi aqualinkd[29175]:   To 0x53 of type    Probe | HEX: 0x10|0x02|0x53|0x00|0x65|0x10|0x03|
Aug 16 12:21:29 raspberrypi aqualinkd[29175]:   To 0x58 of type    Probe | HEX: 0x10|0x02|0x58|0x00|0x6a|0x10|0x03|
Aug 16 12:21:30 raspberrypi aqualinkd[29175]:   To 0x59 of type    Probe | HEX: 0x10|0x02|0x59|0x00|0x6b|0x10|0x03|
Aug 16 12:21:30 raspberrypi aqualinkd[29175]:   To 0x5a of type    Probe | HEX: 0x10|0x02|0x5a|0x00|0x6c|0x10|0x03|
Aug 16 12:21:30 raspberrypi aqualinkd[29175]:   To 0x5b of type    Probe | HEX: 0x10|0x02|0x5b|0x00|0x6d|0x10|0x03|
Aug 16 12:21:30 raspberrypi aqualinkd[29175]:   To 0x60 of type    Probe | HEX: 0x10|0x02|0x60|0x00|0x72|0x10|0x03|
Aug 16 12:21:30 raspberrypi aqualinkd[29175]:   To 0x61 of type    Probe | HEX: 0x10|0x02|0x61|0x00|0x73|0x10|0x03|
Aug 16 12:21:30 raspberrypi systemd[1]: aqualinkd.service: Main process exited, code=exited, status=1/FAILURE
Aug 16 12:21:30 raspberrypi systemd[1]: aqualinkd.service: Unit entered failed state.
Aug 16 12:21:30 raspberrypi systemd[1]: aqualinkd.service: Failed with result 'exit-code'.

**Comment by ballle98** [comment]
```
08:13:21.215 Info:   URI request: '/api '
=================================================================
==14210==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xb4403680 at pc 0x0003e84c bp 0xbe969674 sp 0xbe969240
READ of size 1025 at 0xb4403680 thread T0
    #0 0x3e84b in StrstrCheck(void*, char*, char const*, char const*) (/home/pi/remote-debugging/aqualinkd+0x3e84b)
    #1 0x3eab3 in strstr (/home/pi/remote-debugging/aqualinkd+0x3eab3)
    #2 0x113787 in action_web_request C:\git\AqualinkD/net_services.c:629
    #3 0x118abf in ev_handler C:\git\AqualinkD/net_services.c:1073
    #4 0x13adbb in mg_call C:\git\AqualinkD/mongoose.c:2258
    #5 0x15d5f7 in mg_http_call_endpoint_handler C:\git\AqualinkD/mongoose.c:8463
    #6 0x152557 in mg_http_handler C:\git\AqualinkD/mongoose.c:6374
    #7 0x13adbb in mg_call C:\git\AqualinkD/mongoose.c:2258
    #8 0x13f88b in mg_recv_common C:\git\AqualinkD/mongoose.c:2706
    #9 0x13f8db in mg_if_recv_tcp_cb C:\git\AqualinkD/mongoose.c:2710
    #10 0x14565f in mg_handle_tcp_read C:\git\AqualinkD/mongoose.c:3608
    #11 0x146277 in mg_mgr_handle_conn C:\git\AqualinkD/mongoose.c:3733
    #12 0x148007 in mg_socket_if_poll C:\git\AqualinkD/mongoose.c:3925
    #13 0x13cfeb in mg_mgr_poll C:\git\AqualinkD/mongoose.c:2424
    #14 0xf9def in main_loop C:\git\AqualinkD/aqualinkd.c:1236
    #15 0xf811b in main C:\git\AqualinkD/aqualinkd.c:808
    #16 0xb6d03677 in __libc_start_main (/lib/arm-linux-gnueabihf/libc.so.6+0x16677)

0xb4403680 is located 0 bytes to the right of 1024-byte region [0xb4403280,0xb4403680)
allocated by thread T0 here:
    #0 0xbe557 in malloc (/home/pi/remote-debugging/aqualinkd+0xbe557)
    #1 0x145503 in mg_handle_tcp_read C:\git\AqualinkD/mongoose.c:3572
    #2 0x146277 in mg_mgr_handle_conn C:\git\AqualinkD/mongoose.c:3733
    #3 0x148007 in mg_socket_if_poll C:\git\AqualinkD/mongoose.c:3925
    #4 0x13cfeb in mg_mgr_poll C:\git\AqualinkD/mongoose.c:2424
    #5 0xf9def in main_loop C:\git\AqualinkD/aqualinkd.c:1236
    #6 0xf811b in main C:\git\AqualinkD/aqualinkd.c:808
    #7 0xb6d03677 in __libc_start_main (/lib/arm-linux-gnueabihf/libc.so.6+0x16677)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/home/pi/remote-debugging/aqualinkd+0x3e84b) in StrstrCheck(void*, char*, char const*, char const*)
Shadow bytes around the buggy address:
  0x36880680: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x36880690: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x368806a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x368806b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x368806c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x368806d0:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x368806e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa


```
